//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_1
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Firm { get; set; }
    }
}
